package com.info.ecommerce.modules.product.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(description = "商品描述區塊資訊")
public class ProductDescriptionBlockDTO {

    @Schema(description = "區塊 ID", example = "1")
    private Long id;

    @Schema(description = "商品 ID", example = "1")
    private Long productId;

    @Schema(description = "區塊類型：MANUAL（手動區塊）或 AUTO（自動區塊）", example = "MANUAL")
    private String blockType;

    @Schema(description = "區塊編號（手動區塊：1-3，自動區塊：1-7）", example = "1")
    private Integer blockNumber;

    @Schema(description = "區塊標題", example = "商品特色")
    private String title;

    @Schema(description = "區塊內容", example = "這是商品描述內容...")
    private String content;

    @Schema(description = "區塊圖片URL")
    private String imageUrl;

    @Schema(description = "排序順序", example = "1")
    private Integer blockOrder;

    @Schema(description = "是否啟用", example = "true")
    private Boolean enabled;

    @Schema(description = "是否自動生成", example = "false")
    private Boolean isAutoGenerated;
}

