export * from './product'
export * from './order'
export * from './crm'
export * from './auth'
export * from './types'
export * from './dashboard'
export * from './orderDiscount'
export * from './memberLevel'
export * from './blog'
export * from './orderQA'
export * from './operationLog'

export { default as productApi } from './product'
export { default as orderApi } from './order'
export { default as crmApi } from './crm'
export { default as authApi } from './auth'
export { default as dashboardApi } from './dashboard'
export { default as orderDiscountApi } from './orderDiscount'
export { default as memberLevelApi } from './memberLevel'
export { default as blogApi } from './blog'
export { default as orderQAApi } from './orderQA'
export { default as operationLogApi } from './operationLog'
