/**
 * 商品相關 API
 * @module ProductAPI
 */

import axios from './axios'
import type { ApiResponse, PageResponse } from './types'

/**
 * 商品介面
 * @interface Product
 */
/**
 * 商品介面
 * @interface Product
 */
export interface Product {
  /** 商品 ID */
  id?: number
  /** 商品名稱 */
  name: string
  /** 商品描述 */
  description: string
  /** 商品價格 */
  price: number
  /** 庫存數量 */
  stock: number
  /** 基礎價格 */
  basePrice?: number
  /** 銷售價格 */
  salePrice?: number
  /** 成本價格 */
  costPrice?: number
  /** 商品狀態 */
  status?: 'DRAFT' | 'PUBLISHED' | 'UNPUBLISHED'
  /** 銷售模式 */
  salesMode?: 'NORMAL' | 'PRE_ORDER' | 'TICKET' | 'SUBSCRIPTION' | 'STORE_ONLY'
  /** 分類 ID */
  categoryId?: number | null
  /** 商品圖片 */
  images?: Array<{ imageUrl: string; albumImageId?: number }> | string[]
  /** 商品規格 */
  specifications?: ProductSpecification[]
  /** 商品描述區塊 */
  descriptionBlocks?: ProductDescriptionBlock[]
}

/**
 * 商品規格介面
 * @interface ProductSpecification
 */
export interface ProductSpecification {
  /** 規格 ID */
  id?: number
  /** 商品 ID */
  productId?: number
  /** 規格名稱（例如：顏色:紅色,尺寸:L） */
  specName?: string
  /** 規格 SKU */
  sku?: string
  /** 規格價格 */
  price?: number
  /** 規格成本 */
  cost?: number
  /** 庫存數量 */
  stock?: number
  /** 規格圖片 */
  image?: string
  /** 重量（克） */
  weight?: number
  /** 是否啟用 */
  enabled?: boolean
}

/**
 * 商品描述區塊介面
 * @interface ProductDescriptionBlock
 */
export interface ProductDescriptionBlock {
  /** 區塊 ID */
  id?: number
  /** 商品 ID */
  productId?: number
  /** 區塊類型：MANUAL（手動區塊）或 AUTO（自動區塊） */
  blockType?: 'MANUAL' | 'AUTO'
  /** 區塊編號（手動區塊：1-3，自動區塊：1-7） */
  blockNumber?: number
  /** 區塊標題 */
  title?: string
  /** 區塊內容 */
  content?: string
  /** 區塊圖片URL */
  imageUrl?: string
  /** 排序順序 */
  blockOrder?: number
  /** 是否啟用 */
  enabled?: boolean
  /** 是否自動生成 */
  isAutoGenerated?: boolean
}

/**
 * 商品分類介面
 * @interface ProductCategory
 */
/**
 * 商品分類介面
 * @interface ProductCategory
 */
export interface ProductCategory {
  /** 分類 ID */
  id?: number
  /** 分類名稱 */
  name: string
  /** 分類描述 */
  description?: string
  /** 父分類 ID */
  parentId?: number | null
  /** 分類圖片 */
  image?: string
  /** 分類圖標（Material Icons 名稱） */
  icon?: string
  /** 排序 */
  sortOrder?: number
  /** 是否啟用 */
  enabled?: boolean
}

/**
 * 商品 API 服務
 * @namespace productApi
 */
export const productApi = {
  /**
   * 分頁查詢商品
   * @description 支援分頁查詢商品列表，可依狀態篩選
   * @param {Object} [params] - 查詢參數
   * @param {number} [params.page] - 頁碼（從 0 開始）
   * @param {number} [params.size] - 每頁數量（預設 20）
   * @param {string} [params.status] - 商品狀態篩選 (DRAFT | PUBLISHED | UNPUBLISHED)
   * @returns {Promise<ApiResponse<PageResponse<Product>>>} 分頁商品列表回應
   * @swagger GET /api/products
   * @example
   * const response = await productApi.getProducts({ page: 0, size: 10, status: 'PUBLISHED' })
   */
  getProducts: (params?: any) => {
    return axios.get<any, ApiResponse<Product[]>>('/products', { params })
  },

  /**
   * 取得商品詳情
   * @description 根據商品 ID 獲取完整商品資訊
   * @param {number} id - 商品 ID
   * @returns {Promise<ApiResponse<Product>>} 商品詳情回應
   * @throws {Error} 當商品不存在時拋出 404 錯誤
   * @swagger GET /api/products/{id}
   * @example
   * const response = await productApi.getProduct(123)
   * console.log(response.data.name) // 商品名稱
   */
  getProduct: (id: number) => {
    return axios.get<any, ApiResponse<Product>>(`/products/${id}`)
  },

  /**
   * 創建商品
   * @description 創建新商品，預設狀態為 DRAFT
   * @param {Product} data - 商品資料
   * @param {string} data.name - 商品名稱（必填）
   * @param {string} data.description - 商品描述（必填）
   * @param {number} data.price - 商品價格（必填）
   * @param {number} data.stock - 庫存數量（必填）
   * @param {number} [data.categoryId] - 商品分類 ID
   * @returns {Promise<ApiResponse<Product>>} 創建成功的商品資料
   * @swagger POST /api/products
   * @example
   * const newProduct = await productApi.createProduct({
   *   name: '新商品',
   *   description: '商品描述',
   *   price: 100,
   *   stock: 50,
   *   categoryId: 1
   * })
   */
  createProduct: (data: Product) => {
    return axios.post<any, ApiResponse<Product>>('/products', data)
  },

  /**
   * 更新商品
   * @description 更新指定商品的資料
   * @param {number} id - 商品 ID
   * @param {Product} data - 更新的商品資料（部分更新）
   * @returns {Promise<ApiResponse<Product>>} 更新後的商品資料
   * @swagger PUT /api/products/{id}
   * @example
   * const updated = await productApi.updateProduct(123, { 
   *   name: '更新後的名稱',
   *   price: 150 
   * })
   */
  updateProduct: (id: number, data: Product) => {
    return axios.put<any, ApiResponse<Product>>(`/products/${id}`, data)
  },

  /**
   * 刪除商品
   * @description 永久刪除指定商品（包含相關圖片、規格等資料）
   * @param {number} id - 商品 ID
   * @returns {Promise<ApiResponse<void>>} 刪除結果
   * @swagger DELETE /api/products/{id}
   * @warning 此操作無法復原
   * @example
   * await productApi.deleteProduct(123)
   */
  deleteProduct: (id: number) => {
    return axios.delete<any, ApiResponse<void>>(`/products/${id}`)
  },

  /**
   * 上架商品
   * @description 將商品狀態設為 PUBLISHED（已上架）
   * @param {number} id - 商品 ID
   * @returns {Promise<ApiResponse<Product>>} 上架後的商品資料
   * @swagger PUT /api/products/{id}/activate
   * @example
   * const activated = await productApi.activateProduct(123)
   * console.log(activated.data.status) // 'PUBLISHED'
   */
  activateProduct: (id: number) => {
    return axios.put<any, ApiResponse<Product>>(`/products/${id}/activate`)
  },

  /**
   * 下架商品
   * @description 將商品狀態設為 UNPUBLISHED（已下架）
   * @param {number} id - 商品 ID
   * @returns {Promise<ApiResponse<Product>>} 下架後的商品資料
   * @swagger PUT /api/products/{id}/deactivate
   * @example
   * const deactivated = await productApi.deactivateProduct(123)
   * console.log(deactivated.data.status) // 'UNPUBLISHED'
   */
  deactivateProduct: (id: number) => {
    return axios.put<any, ApiResponse<Product>>(`/products/${id}/deactivate`)
  },

  /**
   * 從相冊添加圖片到商品
   * @description 將相冊中的圖片批量關聯到指定商品
   * @param {number} productId - 商品 ID
   * @param {number[]} albumImageIds - 相冊圖片 ID 陣列
   * @returns {Promise<ApiResponse<Product>>} 更新後的商品資料（包含新增的圖片）
   * @swagger POST /api/products/{id}/album-images
   * @example
   * const updated = await productApi.addAlbumImages(123, [1, 2, 3])
   * console.log(updated.data.images.length) // 顯示圖片數量
   */
  addAlbumImages: (productId: number, albumImageIds: number[]) => {
    return axios.post<any, ApiResponse<Product>>(`/products/${productId}/album-images`, albumImageIds)
  },

  /**
   * 取得所有分類
   * @description 獲取商品分類列表（支持 100 ~ 600 個分類）
   * @returns {Promise<ApiResponse<ProductCategory[]>>} 商品分類列表
   * @swagger GET /api/product-categories
   * @example
   * const categories = await productApi.getCategories()
   * categories.data.forEach(cat => console.log(cat.name))
   */
  getCategories: () => {
    return axios.get<any, ApiResponse<ProductCategory[]>>('/product-categories')
  }
}

/**
 * 商品規格 API 服務
 * @namespace productSpecificationApi
 */
export const productSpecificationApi = {
  /**
   * 添加商品規格
   */
  addSpecification: (data: ProductSpecification) => {
    return axios.post<any, ApiResponse<ProductSpecification>>('/product-specifications', data)
  },

  /**
   * 批量創建商品規格
   */
  batchAddSpecifications: (data: ProductSpecification[]) => {
    return axios.post<any, ApiResponse<ProductSpecification[]>>('/product-specifications/batch', data)
  },

  /**
   * 更新商品規格
   */
  updateSpecification: (id: number, data: ProductSpecification) => {
    return axios.put<any, ApiResponse<ProductSpecification>>(`/product-specifications/${id}`, data)
  },

  /**
   * 刪除商品規格
   */
  deleteSpecification: (id: number) => {
    return axios.delete<any, ApiResponse<void>>(`/product-specifications/${id}`)
  },

  /**
   * 取得規格詳情
   */
  getSpecification: (id: number) => {
    return axios.get<any, ApiResponse<ProductSpecification>>(`/product-specifications/${id}`)
  },

  /**
   * 取得商品的所有規格
   */
  getProductSpecifications: (productId: number) => {
    return axios.get<any, ApiResponse<ProductSpecification[]>>(`/product-specifications/product/${productId}`)
  }
}

/**
 * 商品描述區塊 API 服務
 * @namespace productDescriptionBlockApi
 */
export const productDescriptionBlockApi = {
  /**
   * 獲取商品的所有描述區塊
   */
  getProductBlocks: (productId: number) => {
    return axios.get<any, ApiResponse<ProductDescriptionBlock[]>>(`/products/${productId}/description-blocks`)
  },

  /**
   * 獲取商品的手動區塊（區塊1~3）
   */
  getManualBlocks: (productId: number) => {
    return axios.get<any, ApiResponse<ProductDescriptionBlock[]>>(`/products/${productId}/description-blocks/manual`)
  },

  /**
   * 獲取商品的自動區塊（區塊1~7）
   */
  getAutoBlocks: (productId: number) => {
    return axios.get<any, ApiResponse<ProductDescriptionBlock[]>>(`/products/${productId}/description-blocks/auto`)
  },

  /**
   * 創建或更新手動區塊
   */
  saveManualBlock: (productId: number, blockNumber: number, data: ProductDescriptionBlock) => {
    return axios.post<any, ApiResponse<ProductDescriptionBlock>>(`/products/${productId}/description-blocks/manual/${blockNumber}`, data)
  },

  /**
   * 初始化商品的自動區塊
   */
  initializeAutoBlocks: (productId: number) => {
    return axios.post<any, ApiResponse<ProductDescriptionBlock[]>>(`/products/${productId}/description-blocks/auto/initialize`)
  },

  /**
   * 更新自動區塊
   */
  updateAutoBlock: (productId: number, blockNumber: number, data: ProductDescriptionBlock) => {
    return axios.put<any, ApiResponse<ProductDescriptionBlock>>(`/products/${productId}/description-blocks/auto/${blockNumber}`, data)
  },

  /**
   * 批量保存描述區塊
   */
  saveBlocks: (productId: number, blocks: ProductDescriptionBlock[]) => {
    return axios.post<any, ApiResponse<ProductDescriptionBlock[]>>(`/products/${productId}/description-blocks/batch`, blocks)
  },

  /**
   * 刪除描述區塊
   */
  deleteBlock: (productId: number, blockId: number) => {
    return axios.delete<any, ApiResponse<void>>(`/products/${productId}/description-blocks/${blockId}`)
  }
}

/**
 * 分類 API 服務
 * @namespace categoryApi
 */
export const categoryApi = {
  /**
   * 取得所有分類
   * @description 獲取所有商品分類列表
   * @returns {Promise<ApiResponse<ProductCategory[]>>} 商品分類列表
   * @swagger GET /api/product-categories
   * @example
   * const categories = await categoryApi.getAllCategories()
   */
  getAllCategories: () => {
    return axios.get<any, ApiResponse<ProductCategory[]>>('/product-categories')
  },

  /**
   * 取得已啟用的分類
   * @description 獲取已啟用的商品分類列表
   * @returns {Promise<ApiResponse<ProductCategory[]>>} 已啟用的分類列表
   * @swagger GET /api/product-categories/enabled
   * @example
   * const categories = await categoryApi.getEnabledCategories()
   */
  getEnabledCategories: () => {
    return axios.get<any, ApiResponse<ProductCategory[]>>('/product-categories/enabled')
  },

  /**
   * 取得頂層分類
   * @description 獲取所有頂層分類（無父分類）
   * @returns {Promise<ApiResponse<ProductCategory[]>>} 頂層分類列表
   * @swagger GET /api/product-categories/top
   * @example
   * const topCategories = await categoryApi.getTopCategories()
   */
  getTopCategories: () => {
    return axios.get<any, ApiResponse<ProductCategory[]>>('/product-categories/top')
  },

  /**
   * 取得子分類
   * @description 獲取指定父分類的子分類列表
   * @param {number} parentId - 父分類 ID
   * @returns {Promise<ApiResponse<ProductCategory[]>>} 子分類列表
   * @swagger GET /api/product-categories/{parentId}/children
   * @example
   * const subCategories = await categoryApi.getSubCategories(1)
   */
  getSubCategories: (parentId: number) => {
    return axios.get<any, ApiResponse<ProductCategory[]>>(`/product-categories/${parentId}/children`)
  },

  /**
   * 取得分類詳情
   * @description 根據分類 ID 獲取分類詳情
   * @param {number} id - 分類 ID
   * @returns {Promise<ApiResponse<ProductCategory>>} 分類詳情
   * @swagger GET /api/product-categories/{id}
   * @example
   * const category = await categoryApi.getCategory(1)
   */
  getCategory: (id: number) => {
    return axios.get<any, ApiResponse<ProductCategory>>(`/product-categories/${id}`)
  },

  /**
   * 創建分類
   * @description 創建新的商品分類
   * @param {ProductCategory} data - 分類資料
   * @param {string} data.name - 分類名稱（必填）
   * @param {number} [data.parentId] - 父分類 ID
   * @param {string} [data.description] - 分類描述
   * @returns {Promise<ApiResponse<ProductCategory>>} 創建成功的分類資料
   * @swagger POST /api/product-categories
   * @example
   * const newCategory = await categoryApi.createCategory({
   *   name: '新分類',
   *   description: '分類描述',
   *   parentId: null
   * })
   */
  createCategory: (data: ProductCategory) => {
    return axios.post<any, ApiResponse<ProductCategory>>('/product-categories', data)
  },

  /**
   * 更新分類
   * @description 更新指定分類的資料
   * @param {number} id - 分類 ID
   * @param {ProductCategory} data - 更新的分類資料
   * @returns {Promise<ApiResponse<ProductCategory>>} 更新後的分類資料
   * @swagger PUT /api/product-categories/{id}
   * @example
   * const updated = await categoryApi.updateCategory(1, {
   *   name: '更新後的分類名稱',
   *   description: '更新後的描述'
   * })
   */
  updateCategory: (id: number, data: ProductCategory) => {
    return axios.put<any, ApiResponse<ProductCategory>>(`/product-categories/${id}`, data)
  },

  /**
   * 刪除分類
   * @description 永久刪除指定分類
   * @param {number} id - 分類 ID
   * @returns {Promise<ApiResponse<void>>} 刪除結果
   * @swagger DELETE /api/product-categories/{id}
   * @warning 此操作無法復原
   * @example
   * await categoryApi.deleteCategory(1)
   */
  deleteCategory: (id: number) => {
    return axios.delete<any, ApiResponse<void>>(`/product-categories/${id}`)
  }
}

export default productApi
