package com.info.ecommerce.modules.product.service;

import com.info.ecommerce.common.exception.BusinessException;
import com.info.ecommerce.modules.product.dto.ProductDescriptionBlockDTO;
import com.info.ecommerce.modules.product.entity.ProductDescriptionBlock;
import com.info.ecommerce.modules.product.repository.ProductDescriptionBlockRepository;
import com.info.ecommerce.modules.product.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class ProductDescriptionBlockService {

    private final ProductDescriptionBlockRepository blockRepository;
    private final ProductRepository productRepository;

    /**
     * 獲取商品的所有描述區塊
     */
    public List<ProductDescriptionBlockDTO> getProductBlocks(Long productId) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }
        List<ProductDescriptionBlock> blocks = blockRepository.findByProductIdOrderByBlockOrderAsc(productId);
        return blocks.stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /**
     * 獲取商品的手動區塊（區塊1~3）
     */
    public List<ProductDescriptionBlockDTO> getManualBlocks(Long productId) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }
        List<ProductDescriptionBlock> blocks = blockRepository.findByProductIdAndBlockTypeOrderByBlockOrderAsc(productId, "MANUAL");
        return blocks.stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /**
     * 獲取商品的自動區塊（區塊1~7）
     */
    public List<ProductDescriptionBlockDTO> getAutoBlocks(Long productId) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }
        List<ProductDescriptionBlock> blocks = blockRepository.findByProductIdAndBlockTypeOrderByBlockOrderAsc(productId, "AUTO");
        return blocks.stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /**
     * 創建或更新手動區塊
     */
    @Transactional
    public ProductDescriptionBlockDTO saveManualBlock(Long productId, Integer blockNumber, ProductDescriptionBlockDTO dto) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }
        if (blockNumber < 1 || blockNumber > 3) {
            throw new BusinessException("手動區塊編號必須在1-3之間");
        }

        ProductDescriptionBlock block = blockRepository
                .findByProductIdAndBlockTypeAndBlockNumber(productId, "MANUAL", blockNumber)
                .orElse(ProductDescriptionBlock.builder()
                        .productId(productId)
                        .blockType("MANUAL")
                        .blockNumber(blockNumber)
                        .blockOrder(blockNumber)
                        .isAutoGenerated(false)
                        .build());

        block.setTitle(dto.getTitle());
        block.setContent(dto.getContent());
        block.setImageUrl(dto.getImageUrl());
        if (dto.getEnabled() != null) {
            block.setEnabled(dto.getEnabled());
        }

        block = blockRepository.save(block);
        return toDTO(block);
    }

    /**
     * 初始化商品的自動區塊（如果不存在則創建）
     */
    @Transactional
    public List<ProductDescriptionBlockDTO> initializeAutoBlocks(Long productId) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }

        List<ProductDescriptionBlock> autoBlocks = new ArrayList<>();
        for (int i = 1; i <= 7; i++) {
            if (!blockRepository.existsByProductIdAndBlockTypeAndBlockNumber(productId, "AUTO", i)) {
                ProductDescriptionBlock block = ProductDescriptionBlock.builder()
                        .productId(productId)
                        .blockType("AUTO")
                        .blockNumber(i)
                        .blockOrder(3 + i) // 自動區塊從4開始排序
                        .isAutoGenerated(true)
                        .enabled(true)
                        .title("自動區塊 " + i)
                        .content("")
                        .build();
                autoBlocks.add(blockRepository.save(block));
            }
        }
        return autoBlocks.stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /**
     * 更新自動區塊（僅允許更新內容，不允許修改結構）
     */
    @Transactional
    public ProductDescriptionBlockDTO updateAutoBlock(Long productId, Integer blockNumber, ProductDescriptionBlockDTO dto) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }
        if (blockNumber < 1 || blockNumber > 7) {
            throw new BusinessException("自動區塊編號必須在1-7之間");
        }

        ProductDescriptionBlock block = blockRepository
                .findByProductIdAndBlockTypeAndBlockNumber(productId, "AUTO", blockNumber)
                .orElseThrow(() -> new BusinessException("自動區塊不存在，請先初始化"));

        // 只允許更新內容相關欄位
        if (dto.getTitle() != null) {
            block.setTitle(dto.getTitle());
        }
        if (dto.getContent() != null) {
            block.setContent(dto.getContent());
        }
        if (dto.getImageUrl() != null) {
            block.setImageUrl(dto.getImageUrl());
        }
        if (dto.getEnabled() != null) {
            block.setEnabled(dto.getEnabled());
        }

        block = blockRepository.save(block);
        return toDTO(block);
    }

    /**
     * 批量保存描述區塊
     */
    @Transactional
    public List<ProductDescriptionBlockDTO> saveBlocks(Long productId, List<ProductDescriptionBlockDTO> blocks) {
        if (!productRepository.existsById(productId)) {
            throw new BusinessException("商品不存在");
        }

        List<ProductDescriptionBlock> savedBlocks = new ArrayList<>();
        for (ProductDescriptionBlockDTO dto : blocks) {
            ProductDescriptionBlock block;
            if (dto.getId() != null) {
                block = blockRepository.findById(dto.getId())
                        .orElseThrow(() -> new BusinessException("區塊不存在"));
            } else {
                block = new ProductDescriptionBlock();
                block.setProductId(productId);
                block.setBlockType(dto.getBlockType());
                block.setBlockNumber(dto.getBlockNumber());
                if (dto.getBlockOrder() == null) {
                    if ("MANUAL".equals(dto.getBlockType())) {
                        block.setBlockOrder(dto.getBlockNumber());
                    } else {
                        block.setBlockOrder(3 + dto.getBlockNumber());
                    }
                } else {
                    block.setBlockOrder(dto.getBlockOrder());
                }
                block.setIsAutoGenerated("AUTO".equals(dto.getBlockType()));
            }

            block.setTitle(dto.getTitle());
            block.setContent(dto.getContent());
            block.setImageUrl(dto.getImageUrl());
            if (dto.getEnabled() != null) {
                block.setEnabled(dto.getEnabled());
            }

            savedBlocks.add(blockRepository.save(block));
        }

        return savedBlocks.stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /**
     * 刪除描述區塊
     */
    @Transactional
    public void deleteBlock(Long blockId) {
        if (!blockRepository.existsById(blockId)) {
            throw new BusinessException("區塊不存在");
        }
        blockRepository.deleteById(blockId);
    }

    /**
     * 刪除商品的所有描述區塊
     */
    @Transactional
    public void deleteProductBlocks(Long productId) {
        blockRepository.deleteByProductId(productId);
    }

    private ProductDescriptionBlockDTO toDTO(ProductDescriptionBlock entity) {
        ProductDescriptionBlockDTO dto = new ProductDescriptionBlockDTO();
        BeanUtils.copyProperties(entity, dto);
        return dto;
    }
}

