package com.info.ecommerce.modules.product.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 商品描述區塊
 * 支持3個手動區塊（區塊1~3）和7個自動區塊
 */
@Entity
@Table(name = "product_description_block", indexes = {
    @Index(name = "idx_product_id", columnList = "product_id"),
    @Index(name = "idx_block_type", columnList = "block_type"),
    @Index(name = "idx_block_order", columnList = "block_order")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProductDescriptionBlock {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 商品 ID
    @Column(name = "product_id", nullable = false)
    private Long productId;

    // 區塊類型：MANUAL（手動區塊1~3）或 AUTO（自動區塊1~7）
    @Column(name = "block_type", nullable = false, length = 20)
    private String blockType; // MANUAL 或 AUTO

    // 區塊編號（1-3 為手動區塊，1-7 為自動區塊）
    @Column(name = "block_number", nullable = false)
    private Integer blockNumber;

    // 區塊標題
    @Column(columnDefinition = "NVARCHAR(200)")
    private String title;

    // 區塊內容（支持富文本）
    @Column(columnDefinition = "NVARCHAR(MAX)")
    private String content;

    // 區塊圖片URL
    @Column(length = 500)
    private String imageUrl;

    // 排序順序
    @Column(name = "block_order", nullable = false)
    private Integer blockOrder;

    // 是否啟用
    @Column
    private Boolean enabled;

    // 是否自動生成（自動區塊為true，手動區塊為false）
    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated;

    // 創建時間
    @Column(nullable = false)
    private LocalDateTime createdAt;

    // 更新時間
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        if (this.enabled == null) {
            this.enabled = true;
        }
        if (this.isAutoGenerated == null) {
            this.isAutoGenerated = "AUTO".equals(this.blockType);
        }
        if (this.blockOrder == null) {
            // 手動區塊：1-3，自動區塊：4-10
            if ("MANUAL".equals(this.blockType)) {
                this.blockOrder = this.blockNumber;
            } else {
                this.blockOrder = 3 + this.blockNumber; // 自動區塊從4開始
            }
        }
    }

    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}

